<?php

namespace AppBundle\Repository;

use \Doctrine\DBAL\Types\Type as DataType;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{
	public function import($data)
	{
		// Use pure SQL as is much more faster
        $sql = "INSERT INTO Transaction(transaction_id, store_id, total_amount, currency, created_at)
                VALUES (:transactionId, :storeId, :totalAmount, :currency, :createdAt)";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        
        $stmt->bindValue( "transactionId", $data['TRANSACTION ID'] );
        $stmt->bindValue( "storeId", $data['STORE ID'] );
        $stmt->bindValue( "totalAmount", $data['TOTAL AMOUNT'] );
        $stmt->bindValue( "currency", $data['CURRENCY'] );
        $stmt->bindValue( "createdAt", new \Datetime($data['CREATED AT']), DataType::DATETIME );

        $stmt->execute();
	}
}
